### ISSUE TITLE
Plugin doesn't function + Discord invite expired

### ISSUE THREAD

**Issue by Pulz-TCP** [kristi71111/Personal-Weather#1]
Hey, decided to check out your plugin- doesn't appear to function on 
    SpongeForge: 1.12.2-2838-7.2.2
    Minecraft Forge: 14.23.5.2854
    Luckperms: 5.1.55

The sky colour changes, but reverts to the server's as soon as you move.
Also just wanted to point out that the invite on Ore isn't valid.

Thanks

**Comment by kristi71111** [comment]
Hey just saw this. Do join the discord [here](https://discord.gg/RwkTZpn) and we can discuss the issue there.

**Comment by Pulz-TCP** [comment]
This issue was caused by Dynamic Surroundings installed Server-side (which is not required, does not serve a purpose). Is not a problem when the mod is only the client.
